### ISSUE TITLE
Wrong version in documentation URL

### ISSUE THREAD

**Issue by afrubin** [kc-lab/dms2dfe#2]
URL for documentation has v1.0.0 hardcoded, but that is not the current release version (nor is it the version of the documentation, according to the header of the header of the documentation page itself).

**Comment by rraadd88** [comment]
Now fixed the issue. 
Updated URL for documentation:  
dms2dfe v1.0.6: http://kc-lab.github.io/dms2dfe/v1.0.6/html/
(http://kc-lab.github.io/dms2dfe would lead to the latest version.)

Note that since links to Pypi packages can not be changed, through recent testing and updates, I had to add subversion to `v1.0.6` (version I submitted to JOSS). So strictly, the latest version is `v1.0.6.2`.
