### ISSUE TITLE
Installation on Debian 9

### ISSUE THREAD

**Issue by afrubin** [kc-lab/dms2dfe#3]
More background and detail is needed to guide the users through the installation process. The required Python version should be clearly and prominently stated in the README.md, installation, and documentation index pages. Supported operating systems should also be listed. As currently described, installation is only possible on Debian-based Linux systems. This is fine, but must be clearly stated.

The installation page and the dependencies page should be merged into a step-by-step installation guide with detailed instructions for novice users. Given dms2dfe's strict dependency version requirements, these instructions should include creation of a package-specific Conda environment. This is especially important because many users will have Anaconda3 installed, and will need to install into a Python 2.7 environment. Including a Conda environment file (https://conda.io/docs/user-guide/tasks/manage-environments.html) with the documentation would further simplify the process. 

Instructions for installing R should be provided. I was able to `apt-get install r-base` but ran into a problem installing DESeq2 due to a broken libxml2 dependency. It seems like it might be this issue: https://stackoverflow.com/questions/37035088/unable-to-install-r-package-due-to-xml-dependency-mismatch I was able to get around it by installing r-base and r-xml via Conda, which had the added benefit of placing R for DESeq2 inside the Python 2.7 Conda environment I had already created to hold all the dms2dfe dependencies.

If possible, installation instructions should be written such that they do not require sudo privileges. Users in institutional environments often can't install software that requires sudo without contacting a sysadmin, which will limit adoption.

dms2dfe installs a lot of additional dependencies into a user directory that may already be present in a typical bioinformatics server environment (e.g. samtools, bowtie2, Trimmomatic). What happens if these tools are already installed? I would prefer to handle installing additional dependencies as part of the installation process rather than have it done automatically as part of the first execution of the program. It is especially problematic that a dms2dfe_dependencies directory containing these dependencies is created everywhere that the dms2dfe program is run.

I encountered the following errors during the installation into a newly-created Debian 9 VM:

* The `pip install .` step of the installation into a new environment fails because numpy is not required in setup.py.

* The `pip install .` step of the installation fails because scikit-bio requires Python 3 as of version 0.5 and the setup.py specifies anything higher than 0.4.1. Requiring version 0.4.1 (changing >= to ==) allows installation to proceed.

* I was unable to install gcc through Anaconda in a new Python 2.7 Conda environment. I encountered this error: https://github.com/ContinuumIO/anaconda-issues/issues/1392 Installing gcc through apt-get seems to work, though.

* The directory name listed in the installation guide is not the same as what is downloaded from GitHub. The GitHub download has the version number appended. This is a minor issue, but one that may trouble a novice user.

**Comment by rraadd88** [comment]
Thank you for the comprehensive review and the suggestions.

To simplify the general installation, I have introduced a conda environment file ([environment.yml](https://raw.githubusercontent.com/rraadd88/dms2dfe/master/environment.yml)) and deployed the package itself onto [Pypi](https://pypi.python.org/pypi/dms2dfe). The documentation is also updated with the your suggestions for simplification (python version, merging of installation and dependencies pages, custom dependencies and so on). Following are the key changes.

1. Installation of dependencies and installation of DESeq2:
A recommended creation of [conda environment](http://kc-lab.github.io/dms2dfe/v1.0.6/html/1installation.html#before-install-recommended) environment, clears these issues.
This would standardardise the instalation and resolve the issue with python dependencies (like numpy, scikit-bio and gcc).

2. Sudo privilages:
The installation of package does not require any sudo privilages. Testing (of installation and analysis) on travis CI are also successfully carried out [without sudo privilages](https://github.com/rraadd88/dms2dfe/blob/master/.travis.yml#L3). 
To avoid the sudo privilage, external dependencies (e.g. samtools, bowtie2, Trimmomatic) are configured to work locally in the directory `dms2dfe_dependencies`. Also, this directory is now configured only with the first use of the package, eliminating "repetition everywhere".

3. Pre-installed dependencies:
For using the external dependencies already present in a typical bioinformatics server environment, one would have to simply add the corresponding paths to the sources in the `projet_directory/cfg/info` file. I have highlighted this info in the [updated docs](http://kc-lab.github.io/dms2dfe/v1.0.6/html/1installation.html#optional-manually-adding-paths-to-dependencies).

4. Other errors during the installation:
Deploying the package onto Pypi has reduced the installation to a simple command (`pip install dms2dfe`) and resolved the issue with directory name after dowloading the release from github. Note that since links to Pypi packages can not be changed, through recent testing and updates, I had to add subversion to `v1.0.6` (version I submitted to JOSS). So currently, the latest version on Pypi is `v1.0.6.2`. By default, `pip` would install the latest version.

**Comment by afrubin** [comment]
I started with a new fresh VM and followed the new set of instructions. Thanks for adding the conda environment file. The installation went much more smoothly, but I did encounter some minor issues and (most importantly) an ImportError when running the program for the first time:

* `gcc` is required for many build steps, and should be listed as a requirement. This should not be a problem for most users, since they are likely to have it installed, but it's better to have the requirement stated explicitly.
* `zlib1g-dev` is required to install `pysam`. As with `gcc`, most users are likely to have it installed but it should be listed as a requirement.

To run the examples as written I also needed command-line `git`. This is obvious, but again should be listed at the start of the installation guide as a requirement for running the example.

After installing those dependencies, I was able to get `dms2dfe` installed and check out the example directory. However, when I went to run `dms2dfe Olson_et_al_2014` I got an ImportError from Biopython: [biopython_importerror.txt](https://github.com/kc-lab/dms2dfe/files/1320549/biopython_importerror.txt)

Here's the output from `conda list` in the environment `dms2dfe` is installed into, so you can see the versions of everything: [conda.txt](https://github.com/kc-lab/dms2dfe/files/1320537/conda.txt)

**Comment by rraadd88** [comment]
I have incorporated the suggested additions to the documentation ([zlib1g-dev and gcc](http://kc-lab.github.io/kc-lab.github.io/dms2dfe/v1.0.6/html/1installation.html#before-install-recommended), [git](http://kc-lab.github.io/kc-lab.github.io/dms2dfe/v1.0.6/html/6test.html#download-and-analyze-datasets)).

Also thanks for sharing the "biopython import error". It seems very strange and rare error as I could not get any trace for it anywhere. Also I could not recapitulate the error from the `conda list`. Since the error is from the biopython code, other packages should not matter much. 

`dms2dfe` would install the latest version version i.e. 1.7. So, I browsed biopython's github repo at version 1.7 and found that `Alphabet` (error: `ImportError: cannot import name Alphabet`) is very much present in [biopython 1.7](https://github.com/biopython/biopython/tree/4d01a84f0aa8f91863075f7f0f074b4b69e53959/Bio). Also, I looked into the old biopython packages and found that `Alphabet` is even present in biopython's [1st release (16 yrs ago)](http://biopython.org/DIST/biopython-1.00a3.tar.gz).

My guess is that somehow, either `path/to/python2.7/site-packages/Bio/Alphabet` directory or `path/to/python2.7/site-packages/Bio/Alphabet/__init__.py` file missing.  And reinstalling the biopython1.7 again may resolve the issue.
Given the difficulty in tracing this issue, I have additionally posted it on the biopython's issue tracker ([link](https://github.com/biopython/biopython/issues/1396)).

Please let me know.

**Comment by afrubin** [comment]
I was able to proceed with the installation by uninstalling the pip version of Biopython and installing it through Anaconda (`conda install biopython`), which downgraded it to 1.69. It's possible that the pip version doesn't work well with conda environments, but in any case adding Biopython to the `environment.yml` ought to solve the issue assuming that `dms2dfe` doesn't require features from Biopython 1.70.

**Comment by rraadd88** [comment]
@peterjc , Many thanks for the very crucial insight.
@afrubin , I will test dms2dfe with biopython==1.69 and make it default. Currently I am out of campus for some days, I will surely resolve the issue then.

**Comment by rraadd88** [comment]
@afrubin, I have successfully tested the latest version (1.70) and incorporated it in the conda env file itself. So, as @peterjc mentioned, biopython would be surely installed  through conda-forge channel.

**Comment by afrubin** [comment]
I've reinstalled on a fresh Debian 9 VM using the `environment.yml` file and current Miniconda installation. Everything worked fine, so I'm happy to close this.
